DevDogs-UGA/Optimal-Schedule-Builder

api/README.md, backend/README.md, database/README.md, docker-compose.yml, services/professor-rating/.gitignore, services/professor-rating/.mvn/wrapper/maven-wrapper.properties, services/professor-rating/mvnw, services/professor-rating/mvnw.cmd, services/professor-rating/pom.xml, services/professor-rating/src/main/java/edu/uga/devdogs/professor_rating/ProfessorRatingApplication.java, services/professor-rating/src/main/resources/application.properties, services/professor-rating/src/test/java/edu/uga/devdogs/professor_rating/ProfessorRatingApplicationTests.java
Changed the directory structure, so that it is coherent with the microservices architecture design pattern in mono-repo project structure. Initialized Spring Boot application for professor-rating service.
=> Change directory structure and initialize Spring Boot application for professor-rating

services/optimize/.gitignore, services/optimize/.mvn/wrapper/maven-wrapper.properties, services/optimize/HELP.md, services/optimize/mvnw, services/optimize/mvnw.cmd, services/optimize/pom.xml, services/optimize/src/main/java/edu/uga/devdogs/optimize/OptimizeApplication.java, services/optimize/src/main/resources/application.properties, services/optimize/src/test/java/edu/uga/devdogs/optimize/OptimizeApplicationTests.java
Created _optimize_ directory under _service_ for the Algorithm team. Initialized Spring Boot application under _optimize_ directory.
=> Created optimize directory and initialized Spring Boot application

services/professor-rating/src/main/java/edu/uga/devdogs/professor_rating/controllers/RESTController.java
Create a sample REST controller with dummy endpoint in accordance with issue #34 .
=> Create REST controller in Rate My Professor Spring Boot Application #34

services/professor-rating/src/main/java/edu/uga/devdogs/professor_rating/controllers/RESTController.java
I don't know if I did this right, but i think I did?
=> created a GET endpoint for aggregate helpfulness rating for RMP

backend/webscraping/Professor.java, services/professor-rating/src/main/java/edu/uga/devdogs/professor_rating/webscraping/Professor.java
Added the Professor class to be used in webscraping; #21
=> Added Professor Class

services/bulletin/.gitignore, services/bulletin/.mvn/wrapper/maven-wrapper.properties, services/bulletin/mvnw, services/bulletin/mvnw.cmd, services/bulletin/pom.xml, services/bulletin/src/main/java/edu/uga/devdogs/bulletin/BulletinApplication.java, services/bulletin/src/main/resources/application.properties, services/bulletin/src/test/java/edu/uga/devdogs/bulletin/BulletinApplicationTests.java, services/bulletin/src/test/java/edu/uga/devdogs/bulletin/TestBulletinApplication.java, services/bulletin/src/test/java/edu/uga/devdogs/bulletin/TestcontainersConfiguration.java, services/course-information/.gitignore, services/course-information/.mvn/wrapper/maven-wrapper.properties, services/course-information/mvnw, services/course-information/mvnw.cmd, services/course-information/pom.xml, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/resources/application.properties, services/course-information/src/test/java/edu/uga/devdogs/course_information/CourseInformationApplicationTests.java
=> added bulletin and course-information spring boot application

services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java
Created a Controller file for the Course-Information. I created some methods with placeholder code that can be altered later on. Moreover, I added proper Spring Web Structure with annotations as well as proper Java documentation for what the methods and the class do.
=> Create a Controller File for Course-Information

services/bulletin/src/main/java/edu/uga/devdogs/bulletin/controller/BulletinController.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
also changed packaged for the bulletin controller
issue #80
=> added service file for course information

services/course-information/src/main/java/edu/uga/devdogs/course_information/webscraping/Course.java
=> Created Course.java

services/bulletin/src/main/java/edu/uga/devdogs/bulletin/controller/BulletinController.java
Fixed business logic 
issue #84
=> Add Endpoints for Co-Reqs and Pre-Requisites in BulletinController

.gitignore, services/bulletin/src/main/java/edu/uga/devdogs/bulletin/controller/BulletinController.java
=> Added get endpoint using new format for special types in bulletin

services/course-information/pom.xml, services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java
I added a GET endpoint to the course-information REST controller to get a list of Course objects matching a given major. I also added import statements for Spring Docs to the file for this REST controller and added the Spring Docs dependency to the pom.xml file for the course-information microservice.
=> added GET endpoint to get courses by major

.gitignore
#160 Add Project Level .gitignore
quick gitignore for vscode and intellij stuff
=> Added Project Level Gitignore

services/course-information/src/main/java/edu/uga/devdogs/course_information/Class/Class.java
DATABASE
Created JPA entity for Class
To-Do: add relationships
=> Created Entity/Class for in the class folder

frontend/src/app/component/Footer.tsx, frontend/src/app/page.tsx
=> Finished Footer Component

services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
I created a method in the service file for the course-information microservice to retrieve a list of Class objects given a time slot and CRN.
=> Created service method to get classes by time slot and CRN

frontend/src/app/component/Footer.tsx, frontend/src/app/components/AddCourses.tsx, frontend/src/app/components/Button.tsx, frontend/src/app/components/SearchFilter.tsx, frontend/tailwind.config.ts
Created AddCourses component with functional criteria tabs 
To-do: 
- replace placeholders with dropdown component
- add search and add button functionality
By Section:
By Instructor:
By CRN:
Note: there are some inconsistencies within the design doc (differing button and tab colors) so I just chose what seemed right.
=> Frontend: Create AddCourses Component

services/bulletin/src/main/java/edu/uga/devdogs/bulletin/services/BulletinCourseService.java
File should be a typical Spring Boot Service implementation with @service annotation File should be in a Services directory within the microservice Package should be correct
Should be javadocs on the service base implementation Branch off of dev and pull request to dev, not main Make sure all files starting with . are removed as they should most likely be gitignored
=> Create a Service File for Bulletin Micro Service #81

services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseNotFoundException.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
Implemented the method mentioned and also created CourseNotFoundException in course-information. 
Also implemented getCourseByAthenaName in course-information controller.
=> Implemented service method for Course_Information (Requirement -> Courses)

services/course-information/src/main/java/edu/uga/devdogs/course_information/Building/Building.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Class/Class.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java
Went in and edited some code so that it would actually work.
=> Edited some work

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/schedule/ScheduleUtil.java, algorithm-prototyping/src/main/resources/professors.json
Created and completed the computeAverageProfessorQuality method in ScehduleUtil.java. In addition, finished the dummy data for professors.json by adding their ratings. Finshes issues #200 and #135.
=> Created the computeAverageProfessorQuality method & completed professors.json dummy data.

services/bulletin/src/main/java/edu/uga/devdogs/bulletin/services/BulletinCourseService.java
Implemented a getClassTypeByCourseId method in BulletinCourseService
Also implemented getCourseByTerm method
=> Implemented service method for bulletin CourseID -> Type of class

services/course-information/src/main/java/edu/uga/devdogs/course_information/Building/BuildingRepository.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseSection/CourseSection.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseSection/CourseSectionRepository.java
It runs now, at least on my machine. There were a couple of issues in some spots including existing methods. I commented out a method that was already in CourseSectionRepository because it was creating issues but that seems like something for someone else to solve.
=> Completed issue and fixed bugs

services/bulletin/src/main/java/edu/uga/devdogs/bulletin/services/BulletinCourseService.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
also add null check for bulletin course microservice
=> Document our current work for backend

services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
Created a service method to get a list of Course objects matching a specified major in the service file for the course information microservice. Added missing description of a parameter in Javadoc comment for another function in the same file. Fixed typo in an inline comment.
=> created service method to get Course List by major

services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
prevent duplicate classes for getClassesByCrnAndTime() service method for service methods by using a seen set
=> Prevent duplicate classes in the time return list

services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/exceptions/CourseNotFoundException.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/exceptions/SectionDetailsNotFoundException.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
cleaned up files by adding some implementations
=> Update + cleanup

services/course-information/src/main/java/edu/uga/devdogs/course_information/Course/CourseRepository.java
added a get course by title method
=> #289 Get course by title

frontend/src/app/components/Footer.tsx, frontend/src/app/layout.tsx
https://github.com/user-attachments/assets/63932f86-60d5-4c9e-bf9d-feb207c1fa2e
=> Fixed Footer

services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java
added a comment to mark it was tested, and the resulting output.
lots of lines were changed to fit the new entity constructors.
=> tested CourseInformationApplication & modified instances of objects

services/bulletin/src/main/java/edu/uga/devdogs/bulletin/controller/BulletinController.java, services/bulletin/src/main/java/edu/uga/devdogs/bulletin/exceptions/CourseNotFoundException.java, services/bulletin/src/main/java/edu/uga/devdogs/bulletin/exceptions/IncorrectArguementsException.java, services/bulletin/src/main/java/edu/uga/devdogs/bulletin/services/BulletinCourseService.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/exceptions/ProfessorNotFoundException.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
just check the files I ain't writing allat
=> Huge cleanup and integration

services/bulletin/src/main/java/edu/uga/devdogs/bulletin/services/BulletinCourseService.java
=> add service method to get preReqs by courseID/crn

services/course-information/src/main/java/edu/uga/devdogs/course_information/Course/Course.java
I updated course.java to include bulletin variables
=> course update

services/course-information/src/main/java/edu/uga/devdogs/course_information/Course/CourseRepository.java
Created method that gets all courses by a certain credit hour.
=> Created getCoursesByCreditHours

services/bulletin/src/main/java/edu/uga/devdogs/bulletin/services/BulletinCourseService.java
I created a service method in the service file for the Bulletin microservice to retrieve the type (e.g. honors, lab, or online) using the given Course Reference Number (CRN).
=> created service method to get course type by CRN

services/bulletin/src/main/java/edu/uga/devdogs/bulletin/controller/BulletinController.java, services/bulletin/src/main/java/edu/uga/devdogs/bulletin/exceptions/SectionNotFoundException.java, services/bulletin/src/main/java/edu/uga/devdogs/bulletin/services/BulletinCourseService.java
=> make huge change to add forgotton service method

frontend/src/app/components/home/CallToAction.tsx, frontend/src/app/credit-data/page.tsx, frontend/src/app/generate-schedule/page.tsx, frontend/src/app/login/page.tsx, frontend/src/app/manual-entry/page.tsx, frontend/src/app/page.tsx, frontend/src/app/past-credits/page.tsx, frontend/src/app/questionnaire/page.tsx, frontend/src/app/route-map/page.tsx, frontend/src/app/saved-plans/page.tsx, frontend/src/app/schedules/page.tsx, frontend/src/app/signup/page.tsx
- Created additional pages that are required for the user workflow mentioned in the diagram.
- Implemented the work flow using the link component from Next.js and adding it within buttons on all of the pages.
- The buttons are to the side on the Homepage.
- Created a login and signup page that can be used when authentication is determined.
- All buttons connected to different pages.
- Additional changes may be required in the future.
=> Implemented User Workflow

README.md, gitWiki/catchUp.md
A article that allows new members to easily access all the information they need.
=> Add catchup.md

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForcePrototype.java
Completed #426. This will be used for both hard and soft constraints in the future. Mainly just created the skeleton code so other team members could start working.
=> Designed the dataPreFilter() method and incorperated its use.

frontend/src/app/saved-plans/page.tsx, frontend/src/app/schedules/layout.tsx
The issue regarding the Homepage CSS Display were resolved by someone else, I corrected the appearance of one of the buttons on the saved-plans page to match the others in term of routing to other pages.
=> Updated button appearance on the saved-plans page

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForcePrototype.java
Changed optimize() instead of generateVaildSchedules() because optimize is the actual function that other groups will interact with.
=> Increased optimize() output to 5 schedules

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForcePrototype.java
Wrote the first check in dataPreFilter
Added exception checking and error handling to generateValidSchedules and optimize
Updates Javadocs accordingly
This closes #428
=> Filled in dataPreFilter

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/schedule/ClassComparator.java, algorithm-prototyping/sample-data-parser/src/main/java/edu/uga/devdogs/sampledataparser/records/Class.java, algorithm-prototyping/sample-data-parser/src/main/java/edu/uga/devdogs/sampledataparser/records/Section.java
Updated the code within Section.java and Class.java to account for the CRNs being integers. Furthermore, refactored ClassComparator.java to use an Integer comparison instead of String. This works to solve #424 .
=> Changed the CRNs to be integers and refactored intersecting code.

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForcePrototype.java, algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/schedule/ClassComparator.java, algorithm-prototyping/sample-data-parser/src/main/java/edu/uga/devdogs/sampledataparser/records/Class.java, algorithm-prototyping/sample-data-parser/src/main/java/edu/uga/devdogs/sampledataparser/records/SConstraints.java, algorithm-prototyping/sample-data-parser/src/main/java/edu/uga/devdogs/sampledataparser/records/Section.java
I added the SConstraints record to keep track of all the constraints the user wants. Furthermore, I added this to the BruteForcePrototype class so that members have the foundation to start working on issues. Finally, I added the conversion of CRNs from Strings to int data types for easier implementation with Frontend.
=> SConstraints record, CRNs conversion, BruteForcePrototype modification.

services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
Building JPA integrated into course information service
=> Building JPA Integrated

services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java
returns list of all building objects
closes #442
=> add getAllBuildings GET endpoint

algorithm-prototyping/src/main/resources/courses.json
One regex command in vscode, just learning how to use github right now.
=> Changing strings to integers in courses.json

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/schedule/ScheduleUtil.java
=> Created sectionToInt helper function to convert section sets into arrays of integers

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForcePrototype.java, algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/schedule/ScheduleUtil.java
=> Changed Optimize to output type int[][] instead of List<Schedule>

services/course-information/src/main/java/edu/uga/devdogs/course_information/webscraping/Pdf.java
Fixes the broken parsing methods. This code still cannot compile because of other peoples' database code and stuff that is broken, but once you comment out all the errors, you can use the webscraping methods.
=> fix broken course scraper

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForceUtil.java, algorithm-prototyping/sample-data-parser/src/main/java/edu/uga/devdogs/sampledataparser/records/SConstraints.java
=> filled in dataPreFilter for gapDay prefStartTime and prefEndTime

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForcePrototype.java, algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForceUtil.java
Moved error handling from generateValidSchedules() to driver. 
Removed null check for getValidSchedules() output in optimize(). 
Updated JavaDocs of getValidSchedules() and optimize() to reflect the movement of error handling. 
Fixed grammar in some comments.
closes #474
=> Created algorithmDriver function in BruteForcePrototype

services/bulletin/src/main/java/edu/uga/devdogs/bulletin/controller/BulletinController.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java
Moved method into Course Information Controller
=> Moved getSpecialCourseTypes

services/course-information/src/main/java/edu/uga/devdogs/course_information/Class/ClassRepository.java
=> Finished the findByCourseSectionID method in Spring

frontend/package-lock.json, frontend/src/app/components/Filters.tsx
Added missing campus locations to Filters.tsx
=> CampusList Additions

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForceUtil.java
=> Wrote daySwitch to convert webscraping day data to useable format.

services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
Made some fixes to the getAllSubjects() method in CourseInformationService.java. E.g. made the return type List&lt;String&gt; instead of List&lt;Course&gt;
=> minor fixes to getAllSubjects()

services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java
=> Creat GET endpoint to get all subjects

algorithm-prototyping/sample-data-parser/src/main/java/edu/uga/devdogs/sampledataparser/records/HConstraints.java, algorithm-prototyping/sample-data-parser/src/main/java/edu/uga/devdogs/sampledataparser/records/SConstraints.java
=> Created HConstraints

algorithm-prototyping/src/main/resources/README.md, algorithm-prototyping/src/main/resources/buildingData/AthensBuildingData.json, algorithm-prototyping/src/main/resources/buildingData/GriffinBuildingData.json, algorithm-prototyping/src/main/resources/buildingData/TiftonBuildingData.json
=> Got the real building data as referenced from #482

frontend/src/app/layout.tsx, frontend/src/app/page.tsx
Reverts DevDogs-UGA/Optimal-Schedule-Builder#519
=> Revert "Corrected Homepage bug with scrolling"

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForcePrototype.java, algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForceUtil.java
=> Generated starter code for this week's issues in Algorithms

services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java
Modified each GET endpoint to return 200 instead of 404 for empty responses. I also added 500 error code annotations where they were missing and made various small fixes like correcting typos.
=> Removed 404 error codes + other fixes

frontend/src/app/schedules/layout.tsx, frontend/src/components/Navbar.tsx
Updated the Navbar component so that it can take in a keyword as a prop to conditionally render elements based on the needs of the page. If the prop is left off, it will default to the normal Navbar. Specifically added a variant for the schedules page using keyword = "schedules". Updated schedules/layout.tsx to use the dynamic Navbar. closes #562
=> Dynamic Navbar

frontend/src/components/survey/QuestionnaireForm.tsx
Updated semester selection dropdown to change the order and years of the options based on the user's current month. For January: (Spring of this year, Summer of this year, Fall of this year), For February - May: (Summer of this year, Fall of this year, Spring of next year), For September - December: (Spring of next year, Summer of next year, Fall of next year). Left functionality the same for June - August.
=> SemesterList Changes

frontend/package-lock.json, frontend/src/app/course-adding/page.tsx, frontend/src/components/courses/AddCourses.tsx
- Addressed issue #567 
- Removed search button
- Added Generate Schedule button and linked the corresponding page
=> Changed buttons on course-adding page

services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/exceptions/BuildingNotFoundException.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
Addressed issue, Add getAllInstructors service method #586
Added a getAllInstructors method that returns a list of all the professors.  
Addressed issue, Add BuildingNotFoundException #574
Added a BuildingNotFoundException in the exceptions package 
Addressed issue, Add getAllInstructors endpoint #585
Added a getAllInstructors endpoint in the CourseInfoController file
=> Added getAllInstructors()

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForceUtil.java
Added dataPreHardFilter function which removes all excluded courses from HConstraints from the input set of courses.
=> dataPreHardFilter function

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForceUtil.java
=> Ensure initial courses method created.

frontend/src/app/course-adding/page.tsx, frontend/src/app/credit-data/page.tsx, frontend/src/app/generate-schedule/page.tsx, frontend/src/app/login/page.tsx, frontend/src/app/past-credits/page.tsx, frontend/src/app/questionnaire/page.tsx, frontend/src/app/route-map/page.tsx, frontend/src/app/saved-plans/page.tsx, frontend/src/app/settings/page.tsx, frontend/src/app/signup/page.tsx, frontend/src/components/Filters.tsx, frontend/src/components/Navbar.tsx, frontend/src/components/courses/AddCourses.tsx, frontend/src/components/schedules/DayClass.tsx, frontend/src/components/ui/Card.tsx, frontend/src/components/ui/DropdownSearchInput.tsx
Removed warnings and commented out unused variables
=> Removed warnings

frontend/src/app/course-adding/page.tsx, frontend/src/app/credit-data/page.tsx, frontend/src/app/generate-schedule/page.tsx, frontend/src/app/login/page.tsx, frontend/src/app/past-credits/page.tsx, frontend/src/app/questionnaire/page.tsx, frontend/src/app/route-map/page.tsx, frontend/src/app/saved-plans/page.tsx, frontend/src/app/settings/page.tsx, frontend/src/app/signup/page.tsx, frontend/src/components/Filters.tsx, frontend/src/components/Navbar.tsx, frontend/src/components/courses/AddCourses.tsx, frontend/src/components/schedules/DayClass.tsx, frontend/src/components/ui/Card.tsx, frontend/src/components/ui/DropdownSearchInput.tsx
Reverts DevDogs-UGA/Optimal-Schedule-Builder#606
=> Revert "Removed warnings"

services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
Fixed errors in CourseInformationService.java so it will compile
=> bug fixing in CourseInfoService

services/course-information/src/main/java/edu/uga/devdogs/course_information/Professor/ProfessorRepository.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
Summary of Changes:
- Implemented two new service methods for retrieving RateMyProfessors data for professors.
- **getProfessorAverageRating(String lastName, String firstName):** Retrieves the average RMP rating for a professor based on their last name and first name.
- **getProfessorTotalReviews(String lastName, String firstName):** Retrieves the total number of RMP reviews for a professor based on their last name and first name.
- Both methods use `findByLastNameAndFirstNameIgnoreCase` from the `ProfessorRepository` to search for the professor.
- Throws a `ProfessorNotFoundException` if the professor is not found.
Files Changed:
1. **CourseInformationService.java**
- Added methods to retrieve the average rating and total reviews for a professor.
- These methods access the …
=> Added methods to retrieve professor's RMP average rating and total reviews

services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
Summary:
Implemented **getAvgProfessorRatings** and **getNumProfessorRatings** in _CourseInfoController_.
Both functions call their respective service method as instructed in the issues.
Both functions utilize ProfessorNotFoundException 
Both functions return ResponseEntity of appropriate type
**/avgRating**
Description: This endpoint retrieves the average rating of a professor based on RateMyProfessor reviews.
Parameters:
lname: String | Professor's last name
fname: String | Professor's first nme
Responses:
200 OK: Successfully retrieved the average rating.
204 No Content: No data found for the professor (professor is not in DB).
500 Internal Server Error: An unexpected error occurred.
**/numRatings**
Description: This endpoint retrieves the total number of reviews for a professor on …
=> GET Endpoints getAvgProfessorRatings() and getNumProfessorRatings()

services/course-information/src/main/java/edu/uga/devdogs/course_information/controller/CourseInfoController.java
Frontend needs an endpoint to get section details by crn, so I added it back.
=> added getSectionDetails back

algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForcePrototype.java, algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/BruteForceUtil.java, algorithm-prototyping/brute-force-prototype/src/main/java/edu/uga/devdogs/bruteforceprototype/schedule/ScheduleUtil.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/BruteForcePrototype.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/BruteForceUtil.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/records/Class.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/records/Course.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/records/Distances.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/records/HConstraints.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/records/Professor.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/records/SConstraints.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/records/SampleData.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/records/Section.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/schedule/ClassComparator.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/schedule/Schedule.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/schedule/ScheduleUtil.java
Completes issues #654 #649 #542, allowing the algorithm to be tested. All core files have been moved to the Algorithm folder within the backend.
=> Algorithm completion; Ready for testing

services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/resources/buildingData/AthensBuildingData.json
Fixed an error where it said the primary key was trying to be added multiple times.
=> fized duplicate building code bug

services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
Added getLatitude() and getLongitude() methods to CourseInformationService.java for algorithm.
=> added getLatitude and getLongitude

services/course-information/src/main/java/edu/uga/devdogs/course_information/Algorithm/schedule/ScheduleUtil.java
Fixed compile errors in ScheduleUtil.java
=> fixed algo stuff

frontend/public/images/timeIcon 2.svg, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseSection/CourseSection.java
=> Fixed the CourseHour Display

frontend/public/images/timeIcon 2.svg, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseSection/CourseSection.java
Reverts DevDogs-UGA/Optimal-Schedule-Builder#674
=> Revert "Fixed the CourseHour Display"

services/course-information/src/main/java/edu/uga/devdogs/course_information/Course/CourseRepository.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseSection/CourseSection.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseSection/CourseSectionRepository.java, services/course-information/src/main/resources/application.properties
meeting times and days populate and it now runs.
=> fixed bugs and now database populates correctly

frontend/src/app/course-adding/page.tsx, frontend/src/app/page.tsx, frontend/src/app/saved-plans/choose-plan/page.tsx, frontend/src/app/schedules/page.tsx
=> Fixed Webpage flows

services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/ProfessorService.java
Reverts DevDogs-UGA/Optimal-Schedule-Builder#695
=> Revert "Revert "Here are the beginning steps. #545""

services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Professor/Professor.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Professor/ProfessorRepository.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/ProfessorService.java
[We still need to change the file path as we can't reach the Scraper Currently.](https://github.com/DevDogs-UGA/Optimal-Schedule-Builder/pull/716)
=> Continued Adding Professor to Database

services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
Uncommented some code in the getAllSubjects() service method because it no longer causes errors.
=> uncommented getAllSubjects()

frontend/src/components/schedules/DayClass.tsx
=> Restyle Timestamps for WeekSchedule

services/course-information/src/main/java/edu/uga/devdogs/course_information/Class/ClassEntity.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Course/Course.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseSection/CourseSection.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseSection/CourseSectionRepository.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Professor/Professor.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/webscraping/RateMyProfessorScraper.java, services/course-information/src/main/resources/application.properties, services/course-information/src/main/resources/buildingData/AthensBuildingData.json
Also am attempted to get professor to work and optomize it.
=> Worked on changing time format

.github/workflows/frontend.yml, frontend/package-lock.json, frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/schedules/DayClass.tsx, pnpm-lock.yaml
=> Updated default pre/co reqs

services/course-information/pom.xml, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/webscraping/ProfessorRating.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/webscraping/RateMyProfessorScraper.java
The link web scraping was using isn't working anymore and only returns a 404 error. I tried some other things, but it appears we need an API key to continue with RMP data. I initialized them to realistic values.
=> I removed getting RMP data in the CIA.

services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java
I fixed the errors with LocalTime in the getRecommendedSchedules service method used by the getRecommendedSchedules endpoint. Also fixed some issues in getLatitude and getLongitude since buildingCode is stored as a String now.
=> fixed algo endpoint, getLatitude, getLongitude

services/course-information/pom.xml, services/course-information/src/main/java/edu/uga/devdogs/course_information/Building/Building.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Class/ClassEntity.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Course/Course.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseInformationApplication.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseSection/CourseSection.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/CourseSection/CourseSectionRepository.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/Professor/Professor.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/service/CourseInformationService.java, services/course-information/src/main/java/edu/uga/devdogs/course_information/webscraping/DescriptionScraper.java, services/course-information/src/main/resources/application.properties
Needed to alter paths, debug, etc, and figure out how to get into the server for AWS. Used parent and child style annotation for fixing bidirectional relationships.
=> Set up project to run on AWS and fixed infinite recursion bug between biderectional relationships.

frontend/package-lock.json, frontend/src/components/schedules/DayClass.tsx, frontend/src/components/schedules/WeekSchedule.tsx
=> ACTUALLY restyled timestamps  for Weekschedule component
